version: 0.2

env:
  secrets-manager:
    PYPI_TOKEN: "prod/pypi:pypi-token"

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_INITIATOR
      - echo $CODEBUILD_SRC_DIR
      - export ACTOR_ID=$(echo $CODEBUILD_INITIATOR | cut -d'/' -f2)
      - echo $ACTOR_ID
      - python -m venv venv
      - . venv/bin/activate
      - python -m pip install --upgrade pip
      - pip install urllib3==1.26.15 twine build --upgrade
  build:
    commands:
      - python -m build
  post_build:
    commands:
      - twine upload dist/* -u __token__ -p "${PYPI_TOKEN}"

