version: 0.2

env:
  secrets-manager:
    PYPI_TOKEN: "prod/pypi:pypi-token"

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - BRANCH=$(echo $CODEBUILD_WEBHOOK_BASE_REF | sed 's/refs\/heads\///')
      - echo branch $BRANCH
      - echo branch $CODEBUILD_WEBHOOK_BASE_REF
      - python -m venv venv
      - . venv/bin/activate
      - python -m pip install --upgrade pip
      - pip install urllib3==1.26.15 twine build --upgrade
  build:
    commands:
      - python -m build
  post_build:
    commands:
      - twine upload dist/* -u __token__ -p "${PYPI_TOKEN}"
