version: 0.2

env:
  secrets-manager:
    PYPI_TOKEN: arn:aws:secretsmanager:eu-central-1:495963541969:secret:prod/pypi-GO6Dnm:pypi-token

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - curr_working_dir=`pwd`
      - sed -i "s/TOKEN_REPLACE/${PYPI_TOKEN}/g" $curr_working_dir/.pypirc
      - cat $curr_working_dir/.pypirc
      # - export PIP_CONFIG_FILE=$curr_working_dir/.pypirc
      - python3 -m venv venv
      - source venv/bin/activate
      - python3 -m pip install --upgrade pip
      - pip3 install twine build --upgrade
  build:
    commands:
      - python3 -m build
  post_build:
    commands:
      - twine upload dist/*
