version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.9
    pre_build:
        commands:
            - python3 -m venv venv
            - source venv/bin/activate
            - python3 -m pip install --upgrade pip
            - pip3 install twine build --upgrade
    build:
        commands:
            - python3 -m build
    post_build:
        commands:
            - twine upload --repository codeartifact dist/*
