version: 0.2

env:
  secrets-manager:
    PYPI_TOKEN: arn:aws:secretsmanager:eu-central-1:495963541969:secret:prod/pypi-GO6Dnm:pypi-token

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - python -m venv venv
      - . venv/bin/activate
      - python -m pip install --upgrade pip
      - pip install requests==2.28.0 twine build --upgrade
  build:
    commands:
      - python -m build
  post_build:
    commands:
      - twine upload dist/* -u __token__ -p "${PYPI_TOKEN}" --force
